""" BANCO DE DADOS
    -SQL (LINGUAGEM DE CONSULTA ESTRUTURADA)
    -EXEMPLO:
        - SELECT * FROM CLIENTES;
        - iRA CONSULTAR O BD na Tabela Clientes

        -SGBD:
           -GERENCIAR PERMISSÕES DE ACESSO
"""
